-- DDL Oracle 12cR2 baseado no DER fornecido
-- Cria MAQUINA_AUTONOMA, FUNCIONARIO, LEITURA_SENSORES, MANUTENCAO
-- PKs como IDENTITY, checks e FKs (sem ON DELETE).

/* 1) MAQUINA_AUTONOMA */
CREATE TABLE MAQUINA_AUTONOMA (
  ID_MAQUINA         NUMBER GENERATED ALWAYS AS IDENTITY,
  MODELO             VARCHAR2(50) NOT NULL,
  TIPO               VARCHAR2(50) NOT NULL,
  DATA_INSTALACAO    DATE DEFAULT SYSDATE NOT NULL,
  ULTIMA_MANUTENCAO  DATE,
  CONSTRAINT PK_MAQUINA_AUTONOMA PRIMARY KEY (ID_MAQUINA),
  CONSTRAINT CHK_MAQUINA_TIPO CHECK (TIPO IN ('Solda','Corte','Montagem','Pintura'))
);

-- Índice sugerido para consultas por modelo/tipo (opcional)
CREATE INDEX IDX_MAQUINA_MODELO ON MAQUINA_AUTONOMA(MODELO);

--------------------------------------------------------------------------------
/* 2) FUNCIONARIO */
CREATE TABLE FUNCIONARIO (
  ID_FUNCIONARIO     NUMBER GENERATED ALWAYS AS IDENTITY,
  NOME               VARCHAR2(100) NOT NULL,
  DATA_NASCIMENTO    DATE NOT NULL,
  IDADE              NUMBER NOT NULL,
  SALARIO            NUMBER(10,2) NOT NULL,
  CARGO              VARCHAR2(50) NOT NULL,
  CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (ID_FUNCIONARIO),
  CONSTRAINT CHK_FUNCIONARIO_SALARIO CHECK (SALARIO >= 1518)
);

CREATE INDEX IDX_FUNCIONARIO_NOME ON FUNCIONARIO(NOME);

--------------------------------------------------------------------------------
/* 3) LEITURA_SENSORES */
CREATE TABLE LEITURA_SENSORES (
  ID_LEITURA_SENSORES    NUMBER GENERATED ALWAYS AS IDENTITY,
  ID_MAQUINA             NUMBER, -- pode ser NULO (leitura "órfã"/teste)
  VIBRACAO               NUMBER(10,2) NOT NULL,
  TEMPERATURA            NUMBER(10,2) NOT NULL,
  VELOCIDADE_MOTOR       NUMBER NOT NULL,
  DIAS_ULTIMA_MANUTENCAO NUMBER NOT NULL,
  FALHA                  NUMBER(1) NOT NULL,
  CONSTRAINT PK_LEITURA_SENSORES PRIMARY KEY (ID_LEITURA_SENSORES),
  CONSTRAINT CHK_VIBRACAO_RANGE CHECK (VIBRACAO BETWEEN 0 AND 100),
  CONSTRAINT CHK_TEMPERATURA_RANGE CHECK (TEMPERATURA BETWEEN -50 AND 150),
  CONSTRAINT CHK_VELOCIDADE_RANGE CHECK (VELOCIDADE_MOTOR BETWEEN 0 AND 10000),
  /* opcional: garantir dias não-negativos */
  CONSTRAINT CHK_DIAS_ULT_MANUT_GE0 CHECK (DIAS_ULTIMA_MANUTENCAO >= 0),
  CONSTRAINT CHK_FALHA_VALUES CHECK (FALHA IN (0,1)),
  /* FK - referencial (ID_MAQUINA é NULLABLE; quando informado deve existir) */
  CONSTRAINT FK_LEITURA_MAQUINA FOREIGN KEY (ID_MAQUINA)
    REFERENCES MAQUINA_AUTONOMA (ID_MAQUINA)
    -- sem ON DELETE, padrão RESTRICT/NO ACTION
);

CREATE INDEX IDX_LEITURA_ID_MAQUINA ON LEITURA_SENSORES(ID_MAQUINA);

--------------------------------------------------------------------------------
/* 4) MANUTENCAO */
CREATE TABLE MANUTENCAO (
  ID_MANUTENCAO     NUMBER GENERATED ALWAYS AS IDENTITY,
  DATA_MANUTENCAO   DATE NOT NULL,
  ID_MAQUINA        NUMBER NOT NULL,
  ID_FUNCIONARIO    NUMBER NOT NULL,
  CONSTRAINT PK_MANUTENCAO PRIMARY KEY (ID_MANUTENCAO),
  CONSTRAINT FK_MANUTENCAO_MAQUINA FOREIGN KEY (ID_MAQUINA)
    REFERENCES MAQUINA_AUTONOMA (ID_MAQUINA),
  CONSTRAINT FK_MANUTENCAO_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
    REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE INDEX IDX_MANUTENCAO_ID_MAQUINA ON MANUTENCAO(ID_MAQUINA);
CREATE INDEX IDX_MANUTENCAO_ID_FUNCIONARIO ON MANUTENCAO(ID_FUNCIONARIO);

--------------------------------------------------------------------------------
-- Observações / Sugestões:
-- 1) As FK são criadas sem cláusula ON DELETE conforme especificado (comportamento padrão: RESTRICT/NO ACTION).
-- 2) Caso queira garantir que DATA_INSTALACAO receba hora atual: DEFAULT SYSTIMESTAMP em vez de SYSDATE.
-- 3) Avalie criar constraints/seq de auditoria (created_by, created_at, updated_at) se necessário para rastreabilidade.
-- 4) Se for necessário desempenho em consultas por tempo, crie índices/particionamento em LEITURA_SENSORES por coluna de data (se adicionada).
-- 5) Ajuste os nomes das constraints caso haja padronização diferente no seu ambiente.
